### PR TITLE
New animated polygonal art for fearmonger

### PR DESCRIPTION
**Pull request by insomniacUNDERSCORElemon**
Aside from an attack idle animation (scanning eyes), has stare and defeated animations.

Feel free to modify. Particularly the size/placement of the feet (and final width of pupil lines w/staring animation) as I wasn't sure how it'd look in the final render (particularly worried that details would be messed up if too small)

As before, still needs animations to be called. And adding in the first place this time, as this is a new addition.

### CODE REVIEW

**Comment by db0** [comment]
Hm, The pupils seems to get out of alignment during the animation

**Comment by insomniacUNDERSCORElemon** [comment]
That was intentional (like chameleon eyes) like it is searching individually with each eye for something to focus on, maybe it does look a bit derpy. Although some of my point with the animation is that it's not focused on you to contrast with when it is staring... just like how the pupils go from cute to creepy when it's staring.

If you don't like it, feel free to change it or I can. If you want them all aligned, they could all be animated with 1 track via a position2D node (for position at least).

**Comment by db0** [comment]
Nono, I meant, when they're resting, they're not aligned :) I understood what you were going for and I liked it.

I improved the stare animation and added code to be able to call it. If you add special animations in the future, all you need to do is make their name match the intent.

**Comment by insomniacUNDERSCORElemon** [comment]
> they're not aligned inside the white :)

Alright yeah, I didn't exactly make it exact (in cases where snapping wasn't a great option at least).

> all you need to do is make their name match the intent's name (case sensitive).

OK, but I don't see why you need to bring capital letters into the whole ordeal. Doesn't seem useful IMO.

**Comment by db0** [comment]
The intent names are presented to the player, so they need to be proper english. I may even add whitespace in the future ;) 

To avoid me calling `.lower()` and `.capitalize()` all the time and messing with underscores, it's better to just match the animation name to the dictionary key.

**Comment by insomniacUNDERSCORElemon** [comment]
IMO it wouldn't be noteworthy if it weren't capitalized. They aren't in complete sentences either...

Although it is my personal preference for lowercase (and I understand preference), my wording with that was mostly intended to be comedic.

**Comment by db0** [comment]
Hah fair enough! Difficult to tell humor when one doesn't know the other person well enough. :D

**Comment by insomniacUNDERSCORElemon** [comment]
You forgot to remove the line `"_character_art": "nobody",`, causing it to not load.

The way you modified the pupils, now it's always staring which kinda ruins the effect IMO. That and you didn't zero the properties that you added for the stare animation, if you watch the stare animation mid-way and then run the project the eyes will not be properly placed (the pupils will be floating in the air, you can easily see this in the editor just by switching tracks mid-way).

Also it's as I'd feared, the stare effect doesn't actually work all too well due to how small enemies are displayed. It'd be best if you could scale enemies up some (especially when you don't intend battles of 4+ anyways, right?)... the pupil could easily be changed to have 1 less spiral (needs to be wider when full) so it has more space when thinned (but at that point it's just a square with a hook in it, not very good IMO).

---------

For a small detail, with the held keyframes (w/stare animation) it'll probably look better if they're set to zero easing on the beginning of the held frames (that way it actually holds). Forgive me if I actually started that mistake, I can't remember (I did put zero easing w/the held frame in the defeat animation).

**Comment by insomniacUNDERSCORElemon** [comment]
If you don't like the look of it looking away from the player/user, perhaps it should shut its eyes between turns.

**Comment by db0** [comment]
Sure why not. Give it a try

**Pull request merged**
